### ISSUE TITLE
Deploy simple frontend

### ISSUE THREAD

**Issue by nicklasfrahm** [nicklasfrahm/odance#1]
At the domain `odance.dk` a simple website should be visible. There does not need to be any special content.

* Set up DNS records
* Set up GitHub pages
* Set up CI / CD workflow

**Comment by nicklasfrahm** [comment]
@OPoziomkowska the first version is available at https://odance.dk.

**Comment by OPoziomkowska** [comment]
Not closed ;p

Best regards
Aleksandra Poziomkowska

**Comment by nicklasfrahm** [comment]
I will reopen this until all checks are green.

**Comment by nicklasfrahm** [comment]
Fixed by implementing the solution described [here](https://github.community/t/certificate-request-error-is-persistent-tls-certificate-cant-be-provisioned/11008/17).

**Comment by nicklasfrahm** [comment]
Redeployments break the webpage. This is caused by the fact that the CNAME file is missing in the generated build output. Commit 6e3b8d6 fixes this bug.
